create table if not exists public.learning_entitlements (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  product_id text not null check (product_id in ('quick-start', 'toolkit')),
  source text not null check (
    source in ('verified-sign-in', 'purchase', 'manual')
  ),
  granted_at timestamptz not null default now(),
  revoked_at timestamptz,
  unique (user_id, product_id)
);

create index if not exists learning_entitlements_active_user_idx
  on public.learning_entitlements (user_id)
  where revoked_at is null;

alter table public.learning_entitlements enable row level security;

revoke all on table public.learning_entitlements from anon;
grant select on table public.learning_entitlements to authenticated;

drop policy if exists "Customers can read their own entitlements"
  on public.learning_entitlements;
create policy "Customers can read their own entitlements"
  on public.learning_entitlements
  for select
  to authenticated
  using (user_id = (select auth.uid()));

create or replace function public.grant_quick_start()
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if auth.uid() is null or not exists (
    select 1
    from auth.users
    where id = auth.uid()
      and email_confirmed_at is not null
  ) then
    raise exception 'A verified user is required'
      using errcode = 'insufficient_privilege';
  end if;

  insert into public.learning_entitlements (
    user_id,
    product_id,
    source,
    revoked_at
  )
  values (auth.uid(), 'quick-start', 'verified-sign-in', null)
  on conflict (user_id, product_id)
  do update set
    source = 'verified-sign-in',
    granted_at = now(),
    revoked_at = null;
end;
$$;

revoke all on function public.grant_quick_start() from public;
revoke all on function public.grant_quick_start() from anon;
grant execute on function public.grant_quick_start() to authenticated;
